name: Build AimLockOb55

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Lấy source code
        uses: actions/checkout@v4

      - name: ☕ Cài Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: 🔧 Cấp quyền Gradle
        run: chmod +x gradlew

      - name: 🏗️ Build APK
        run: ./gradlew assembleDebug --stacktrace

      - name: 🔎 Kiểm tra APK
        run: |
          echo "APK đã build:"
          find . -type f -name "*.apk" -print

      - name: 📦 Xuất APK
        uses: actions/upload-artifact@v4
        with:
          name: AimLockOb55
          path: "**/build/outputs/apk/**/*.apk"
          if-no-files-found: error
